package com.subrat.collections;

import java.util.*;

class Hospital {
	private int hospitalCode;
	private String hospitalName;
	private List<String> listOfTreatments;
	private String contactPerson;
	private String contactNumber;
	private String location;

	public Hospital(int hospitalCode, String hospitalName, List<String> listOfTreatments, String contactPerson,
			String contactNumber, String location) {
		super();
		this.hospitalCode = hospitalCode;
		this.hospitalName = hospitalName;
		this.listOfTreatments = new ArrayList<>(listOfTreatments);
		this.contactPerson = contactPerson;
		this.contactNumber = contactNumber;
		this.location = location;
	}

	public int getHospitalCode() {
		return hospitalCode;
	}

	public void setHospitalCode(int hospitalCode) {
		this.hospitalCode = hospitalCode;
	}

	public String getHospitalName() {
		return hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	public List<String> getListOfTreatments() {
		return listOfTreatments;
	}

	public void setListOfTreatments(List<String> listOfTreatments) {
		this.listOfTreatments = listOfTreatments;
	}

	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Override
	public String toString() {
		return "Hospital [hospitalCode=" + hospitalCode + ", hospitalName=" + hospitalName + ", listOfTreatments="
				+ listOfTreatments + ", contactPerson=" + contactPerson + ", contactNumber=" + contactNumber
				+ ", location=" + location + "]";
	}
	
}
class HospitalService{
	ArrayList<Hospital>hospital=new ArrayList<>();
	public int addHospital(int hospitalCode,String hospitalName,List<String>listOfTreatments,String contactPerson,String contactNumber,String location) {
		hospital.add(new Hospital(hospitalCode,hospitalName,listOfTreatments,contactPerson,contactNumber,location));
		int hospitalCounter=100;
		return hospitalCounter++;
	}
	public Map<Integer,String> getHospitals() {
		Map<Integer,String>m1=new HashMap<>();
		for(Hospital h:hospital) {
			m1.put(h.getHospitalCode(),h.getHospitalName());
		}
		return m1;
	}
	public Hospital  getHospitalDetails(int hospitalCode ) {
		for(Hospital h:hospital){
			if(h.getHospitalCode()==hospitalCode) {
				return h;
			}
		}
		return null;
	}
}

public class HospitalFinder {
	void main() {
		List<String>l1=Arrays.asList("aurthopedic,dentist,dermetologist");
		List<String>l2=Arrays.asList("bone specialist","sk``in specialist");
//		Hospital h1=new Hospital();
	}
}
/*
Program: 1
----------
class Hospital is given to you. Implement the following features in the class.
Variables : 
private : hospitalCode int, hospitalName String,
listOfTreatments List<String>,contactPerson String,
contactNumber String,location String
public : Constructors:
Parameterized Constructor with arguments in the order of 
hospitalName,listOfTreatments,
 contactPerson,contactNumber,location
Methods : public
 Generate All Getters & Setters 
 Generate toString() to return a formatted string as per the below example.
Hospital [hospitalCode=101, hospitalName=YASHODA, listOfTreatments=[Cardiac, ENT, 
Ortho, Pediatric, Gastro], 
contactPerson=MATHEWS, contactNumber=9848222222, location=Sec]
 
A class HospitalService is given to you. Implement the following features in the class.
Methods : public 
addHospital(): This method should receive hospital details 
 as arguments and add to ArrayList of type Hospital and return the generated hospital 
code.
Note : Hospital Code is not given as argument but it should be 
 autogenerated while creating object. It should start from 100.
 
 getHospitals() : This method should return existing hospitals 
names and its codes in the form of Map variable that contains Hospital 
Code as key (Integer) and Hospital name as Value (String).

 getHospitalDetails() : This method should receive hospital code 
as argument and return the matching object of hospital after searching in 
the ArrayList. Return null if object not found.
A class HospitalFinder is given to you with a main method. 
Create multiple Hospital objects and test with the methods of HospitalService class here
*/